plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.0.cjs

packageExtensions:
  "@docsearch/react@*":
    dependencies:
      "@algolia/client-search": "*"
  "postcss-loader@*":
    dependencies:
      "@types/node": "*"
